apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletinboard-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletinboard
  template:
    metadata:
      labels:
        app: bulletinboard # Pod labels
        # The label matches the Service's label selector
    spec:
      containers:
      - name: bb-site
        image: projetosdregisto.azurecr.io/bulletinboard:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bulletinboard-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: bulletinboard
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP