version: '3.5'
services:
  bulletin-board:
    build: .
    ports:
      - "8000:8080"
    networks:
      - bb-net
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql-development
      MYSQL_USER: db_user
      MYSQL_PASSWORD: hello-world
      MYSQL_DATABASE: bulletin-board

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bulletin-board
    ports:
      - "3308:3306"
    networks:
      - bb-net
    volumes:
      - type: volume
        source: bb-vol
        target: /var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql-development
    environment:
      PMA_HOST: mysql-development
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - bb-net
networks:
  bb-net:

volumes:
  bb-vol: