apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: bulletinboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletinboard-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletinboard
  template:
    metadata:
      name: bulletinboard
      labels:
        app: bulletinboard # Pod labels The label matches the Service's label selector
    spec:
      restartPolicy: Always
      containers:
      - name: bb-site
        image: progrub/bulletinboard:1.0
        env:
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: secret
        ports:
        - containerPort: 8080
        
      - name: bb-db
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: secret
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql 
        ports:
        - containerPort: 5432

      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-claim        
---
apiVersion: v1
kind: Service
metadata:
  name: bulletinboard-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bulletinboard
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP