name: Docker App Deployment

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Stop running container
      run: docker stop bb
    - name: Delete container
      run: docker rm bb
    - name: Stop running PostgresSQL container
      run: docker stop postgres
    - name: Delete PostgresSQL container
      run: docker rm postgres
    # - name: Create network
    #   run: docker network create bb-app
    # - name: Create volume
    #   run: docker volume create bb-vol
    - name: Create PostgresSQL container
      run: docker run -d --network bb-app --network-alias postgres-development -v bb-vol:/var/lib/postgres -e POSTGRES_PASSWORD=secret --name postgres postgres:latest
    - name: Create app image
      run: docker build --tag bulletinboard:1.0 .
    - name: Create app container
      run: docker run --publish 8000:8080 --detach --network bb-app -e POSTGRES_HOST=postgres-development -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=secret --name bb bulletinboard:1.0