name: Push to ACR

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: projetosdregisto.azurecr.io
          username: projetosdregisto
          password: 2fxAxhK6uJBCS/gXNnKg5T9TwFc7pqsZ #2 - DBaDwyrsGhb7JVOAa/ignuCYsiGkWJGZ

      - run: |
          docker build --tag bulletinboard:1.0 .
          docker tag bulletinboard:1.0 projetosdregisto.azurecr.io/bulletinboard:1.0
          docker push projetosdregisto.azurecr.io/bulletinboard:1.0 