name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy 
    steps:
      - uses: actions/checkout@v2
      
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        run: |
          docker buildx build --push --platform linux/arm/v7 --tag progrub/bulletinboard:1.0 .