name: Push to ACR

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: projetosdregisto.azurecr.io
          username: projetosdregisto
          password: FkCt=Z4qZYkRQk81fh7Jq5aXkobSkQop #2 - L/aqsHQjjIBA16yurS9VuZPfyjj7CCwR

      - run: |
          docker tag bulletinboard:1.0 projetosdregisto.azurecr.io/bulletinboard:1.0
          docker push projetosdregisto.azurecr.io/bulletinboard:1.0 
          docker tag bulletinboard:2.0 projetosdregisto.azurecr.io/bulletinboard:2.0
          docker push projetosdregisto.azurecr.io/bulletinboard:2.0 
          docker tag mysql:5.6 projetosdregisto.azurecr.io/mysql:5.6
          docker push projetosdregisto.azurecr.io/mysql:5.6