name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "$DOCKERHUB_USERNAME"
          password: "$DOCKERHUB_PASSWORD"
"
      - name: Build and push image
        run: |
          docker buildx build --push --platform linux/arm/v7 --tag progrub/bulletinboard:1.0 .