name: Push to ACR

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: projetosdregisto.azurecr.io
          username: projetosdregisto
          password: WA4FNr310kuDK3+NmBWZDEBJH0eTBdy4 #2 - J=dtegOhuE/R7AT5RBfGIx88xP+0yNEb

      - run: |
          docker build --tag bulletinboard:1.0 .
          docker tag bulletinboard:1.0 projetosdregisto.azurecr.io/bulletinboard:1.0
          docker push projetosdregisto.azurecr.io/bulletinboard:1.0 